//
//  SensorCatalogTable.swift
//  SMCKit
//
//  GENERATED FILE — do not edit by hand.
//  Regenerate with: python3 Scripts/generate-sensor-catalog.py
//
//  Sensor naming data derived from the Stats project
//  (https://github.com/exelban/stats), MIT License:
//
//      Copyright (c) 2019 Serhiy Mytrovtsiy
//
//      Permission is hereby granted, free of charge, to any person obtaining a copy
//      of this software and associated documentation files (the "Software"), to deal
//      in the Software without restriction, including without limitation the rights
//      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//      copies of the Software, and to permit persons to whom the Software is
//      furnished to do so, subject to the following conditions:
//
//      The above copyright notice and this permission notice shall be included in all
//      copies or substantial portions of the Software.
//
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//      SOFTWARE.
//

import Foundation

/// The seeded key → (name, group, type, platform scope) table.
public let kSensorCatalogTable: [SensorCatalogEntry] = [
    SensorCatalogEntry(key: "TA%P", name: "Ambient %", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "Th%H", name: "Heatpipe %", group: .sensor, type: .temperature, platforms: [.intel]),
    SensorCatalogEntry(key: "TZ%C", name: "Thermal zone %", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TC0D", name: "CPU diode", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TC0E", name: "CPU diode virtual", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TC0F", name: "CPU diode filtered", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TC0H", name: "CPU heatsink", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TC0P", name: "CPU proximity", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TCAD", name: "CPU package", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TC%c", name: "CPU core %", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon], average: true),
    SensorCatalogEntry(key: "TC%C", name: "CPU Core %", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon], average: true),
    SensorCatalogEntry(key: "TCGC", name: "GPU Intel Graphics", group: .gpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TG0D", name: "GPU diode", group: .gpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TGDD", name: "GPU AMD Radeon", group: .gpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TG0H", name: "GPU heatsink", group: .gpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TG0P", name: "GPU proximity", group: .gpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "Tm0P", name: "Mainboard", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "Tp0P", name: "Powerboard", group: .system, type: .temperature, platforms: [.intel]),
    SensorCatalogEntry(key: "TB1T", name: "Battery", group: .system, type: .temperature, platforms: [.intel]),
    SensorCatalogEntry(key: "TW0P", name: "Airport", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TL0P", name: "Display", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TI%P", name: "Thunderbolt %", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TH%A", name: "Disk % (A)", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TH%B", name: "Disk % (B)", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TH%C", name: "Disk % (C)", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TTLD", name: "Thunderbolt left", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TTRD", name: "Thunderbolt right", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TN0D", name: "Northbridge diode", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TN0H", name: "Northbridge heatsink", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "TN0P", name: "Northbridge proximity", group: .system, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "Tp09", name: "CPU efficiency core 1", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp0T", name: "CPU efficiency core 2", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp01", name: "CPU performance core 1", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp05", name: "CPU performance core 2", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp0D", name: "CPU performance core 3", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp0H", name: "CPU performance core 4", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp0L", name: "CPU performance core 5", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp0P", name: "CPU performance core 6", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp0X", name: "CPU performance core 7", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tp0b", name: "CPU performance core 8", group: .cpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tg05", name: "GPU 1", group: .gpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tg0D", name: "GPU 2", group: .gpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tg0L", name: "GPU 3", group: .gpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tg0T", name: "GPU 4", group: .gpu, type: .temperature, platforms: [.m1], average: true),
    SensorCatalogEntry(key: "Tm02", name: "Memory 1", group: .sensor, type: .temperature, platforms: [.m1]),
    SensorCatalogEntry(key: "Tm06", name: "Memory 2", group: .sensor, type: .temperature, platforms: [.m1]),
    SensorCatalogEntry(key: "Tm08", name: "Memory 3", group: .sensor, type: .temperature, platforms: [.m1]),
    SensorCatalogEntry(key: "Tm09", name: "Memory 4", group: .sensor, type: .temperature, platforms: [.m1]),
    SensorCatalogEntry(key: "Tp1h", name: "CPU efficiency core 1", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp1t", name: "CPU efficiency core 2", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp1p", name: "CPU efficiency core 3", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp1l", name: "CPU efficiency core 4", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp01", name: "CPU performance core 1", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp05", name: "CPU performance core 2", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp09", name: "CPU performance core 3", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp0D", name: "CPU performance core 4", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp0X", name: "CPU performance core 5", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp0b", name: "CPU performance core 6", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp0f", name: "CPU performance core 7", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tp0j", name: "CPU performance core 8", group: .cpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tg0f", name: "GPU 1", group: .gpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Tg0j", name: "GPU 2", group: .gpu, type: .temperature, platforms: [.m2], average: true),
    SensorCatalogEntry(key: "Te05", name: "CPU efficiency core 1", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Te0L", name: "CPU efficiency core 2", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Te0P", name: "CPU efficiency core 3", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Te0S", name: "CPU efficiency core 4", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf04", name: "CPU performance core 1", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf09", name: "CPU performance core 2", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf0A", name: "CPU performance core 3", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf0B", name: "CPU performance core 4", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf0D", name: "CPU performance core 5", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf0E", name: "CPU performance core 6", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf44", name: "CPU performance core 7", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf49", name: "CPU performance core 8", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf4A", name: "CPU performance core 9", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf4B", name: "CPU performance core 10", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf4D", name: "CPU performance core 11", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf4E", name: "CPU performance core 12", group: .cpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf14", name: "GPU 1", group: .gpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf18", name: "GPU 2", group: .gpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf19", name: "GPU 3", group: .gpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf1A", name: "GPU 4", group: .gpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf24", name: "GPU 5", group: .gpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf28", name: "GPU 6", group: .gpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf29", name: "GPU 7", group: .gpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Tf2A", name: "GPU 8", group: .gpu, type: .temperature, platforms: [.m3], average: true),
    SensorCatalogEntry(key: "Te05", name: "CPU efficiency core 1", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Te0S", name: "CPU efficiency core 2", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Te09", name: "CPU efficiency core 3", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Te0H", name: "CPU efficiency core 4", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tp01", name: "CPU performance core 1", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tp05", name: "CPU performance core 2", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tp09", name: "CPU performance core 3", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tp0D", name: "CPU performance core 4", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tp0V", name: "CPU performance core 5", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tp0Y", name: "CPU performance core 6", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tp0b", name: "CPU performance core 7", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tp0e", name: "CPU performance core 8", group: .cpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg0G", name: "GPU 1", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg0H", name: "GPU 2", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg1U", name: "GPU 1", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg1k", name: "GPU 2", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg0K", name: "GPU 3", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg0L", name: "GPU 4", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg0d", name: "GPU 5", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg0e", name: "GPU 6", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg0j", name: "GPU 7", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tg0k", name: "GPU 8", group: .gpu, type: .temperature, platforms: [.m4], average: true),
    SensorCatalogEntry(key: "Tm0p", name: "Memory Proximity 1", group: .sensor, type: .temperature, platforms: [.m4]),
    SensorCatalogEntry(key: "Tm1p", name: "Memory Proximity 2", group: .sensor, type: .temperature, platforms: [.m4]),
    SensorCatalogEntry(key: "Tm2p", name: "Memory Proximity 3", group: .sensor, type: .temperature, platforms: [.m4]),
    SensorCatalogEntry(key: "Tp00", name: "CPU super core 1", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp04", name: "CPU super core 2", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp08", name: "CPU super core 3", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0C", name: "CPU super core 4", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0G", name: "CPU super core 5", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0K", name: "CPU super core 6", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0O", name: "CPU performance core 1", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0R", name: "CPU performance core 2", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0U", name: "CPU performance core 3", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0X", name: "CPU performance core 4", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0a", name: "CPU performance core 5", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0d", name: "CPU performance core 6", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0g", name: "CPU performance core 7", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0j", name: "CPU performance core 8", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0m", name: "CPU performance core 9", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0p", name: "CPU performance core 10", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0u", name: "CPU performance core 11", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tp0y", name: "CPU performance core 12", group: .cpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tg0U", name: "GPU 1", group: .gpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tg0X", name: "GPU 2", group: .gpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tg0d", name: "GPU 3", group: .gpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tg0g", name: "GPU 4", group: .gpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tg0j", name: "GPU 5", group: .gpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tg1Y", name: "GPU 6", group: .gpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tg1c", name: "GPU 7", group: .gpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "Tg1g", name: "GPU 8", group: .gpu, type: .temperature, platforms: [.m5], average: true),
    SensorCatalogEntry(key: "TaLP", name: "Airflow left", group: .sensor, type: .temperature, platforms: [.appleSilicon]),
    SensorCatalogEntry(key: "TaRF", name: "Airflow right", group: .sensor, type: .temperature, platforms: [.appleSilicon]),
    SensorCatalogEntry(key: "TH0x", name: "NAND", group: .system, type: .temperature, platforms: [.appleSilicon]),
    SensorCatalogEntry(key: "TB1T", name: "Battery 1", group: .system, type: .temperature, platforms: [.appleSilicon]),
    SensorCatalogEntry(key: "TB2T", name: "Battery 2", group: .system, type: .temperature, platforms: [.appleSilicon]),
    SensorCatalogEntry(key: "TW0P", name: "Airport", group: .system, type: .temperature, platforms: [.appleSilicon]),
    SensorCatalogEntry(key: "VCAC", name: "CPU IA", group: .cpu, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VCSC", name: "CPU System Agent", group: .cpu, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VC%C", name: "CPU Core %", group: .cpu, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VCTC", name: "GPU Intel Graphics", group: .gpu, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VG0C", name: "GPU", group: .gpu, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VM0R", name: "Memory", group: .system, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "Vb0R", name: "CMOS", group: .system, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VD0R", name: "DC In", group: .sensor, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VP0R", name: "12V rail", group: .sensor, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "Vp0C", name: "12V vcc", group: .sensor, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VV2S", name: "3V", group: .sensor, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VR3R", name: "3.3V", group: .sensor, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VV1S", name: "5V", group: .sensor, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VV9S", name: "12V", group: .sensor, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "VeES", name: "PCI 12V", group: .sensor, type: .voltage, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "IC0R", name: "CPU High side", group: .sensor, type: .current, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "IG0R", name: "GPU High side", group: .sensor, type: .current, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "ID0R", name: "DC In", group: .sensor, type: .current, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "IBAC", name: "Battery", group: .sensor, type: .current, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "IDBR", name: "Brightness", group: .sensor, type: .current, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "IU1R", name: "Thunderbolt Left", group: .sensor, type: .current, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "IU2R", name: "Thunderbolt Right", group: .sensor, type: .current, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PC0C", name: "CPU Core", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCAM", name: "CPU Core (IMON)", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCPC", name: "CPU Package", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCTR", name: "CPU Total", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCPT", name: "CPU Package total", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCPR", name: "CPU Package total (SMC)", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PC0R", name: "CPU Computing high side", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PC0G", name: "CPU GFX", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCEC", name: "CPU VccEDRAM", group: .cpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCPG", name: "GPU Intel Graphics", group: .gpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PG0C", name: "GPU", group: .gpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PG0R", name: "GPU 1", group: .gpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PG1R", name: "GPU 2", group: .gpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCGC", name: "Intel GPU", group: .gpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PCGM", name: "Intel GPU (IMON)", group: .gpu, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PC3C", name: "RAM", group: .sensor, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PPBR", name: "Battery", group: .sensor, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PDTR", name: "DC In", group: .sensor, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PMTR", name: "Memory Total", group: .sensor, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PSTR", name: "System Total", group: .sensor, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PU1R", name: "Thunderbolt Left", group: .sensor, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PU2R", name: "Thunderbolt Right", group: .sensor, type: .power, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PDBR", name: "Power Delivery Brightness", group: .sensor, type: .power, platforms: [.m1, .m4]),
    SensorCatalogEntry(key: "PBwo", name: "Display Backlight", group: .sensor, type: .power, platforms: [.m5]),
    SensorCatalogEntry(key: "pACC MTR Temp Sensor%", name: "CPU performance core %", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "eACC MTR Temp Sensor%", name: "CPU efficiency core %", group: .cpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "GPU MTR Temp Sensor%", name: "GPU core %", group: .gpu, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "SOC MTR Temp Sensor%", name: "SOC core %", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "ANE MTR Temp Sensor%", name: "Neural engine %", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "ISP MTR Temp Sensor%", name: "Image Signal Processor %", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PMGR SOC Die Temp Sensor%", name: "Power manager die %", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PMU tdev%", name: "Power management unit dev %", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "PMU tdie%", name: "Power management unit die %", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "gas gauge battery", name: "Battery", group: .sensor, type: .temperature, platforms: [.intel, .appleSilicon]),
    SensorCatalogEntry(key: "NAND CH% temp", name: "Disk %s", group: .gpu, type: .temperature, platforms: [.intel, .appleSilicon]),
]
