// GENERATED from Packages/SMCKit/Sources/SMCKit/SensorCatalogTable.swift.
// Regenerate with: bun website/scripts/generate-sensor-catalog.mjs
//
// These are the shipped catalog entries whose keys are literal FourCCs. Wildcard
// families (TC%c and friends) are resolved at runtime against the machine, so they
// are listed as families instead of as fake concrete keys.

export type CatalogEntry = { key: string; name: string; group: string; type: string };

export const CATALOG: CatalogEntry[] = [
  { key: "PC0R", name: "CPU Computing high side", group: "CPU", type: "Power" },
  { key: "PC0C", name: "CPU Core", group: "CPU", type: "Power" },
  { key: "PCAM", name: "CPU Core (IMON)", group: "CPU", type: "Power" },
  { key: "TC0D", name: "CPU diode", group: "CPU", type: "Temperature" },
  { key: "TC0F", name: "CPU diode filtered", group: "CPU", type: "Temperature" },
  { key: "TC0E", name: "CPU diode virtual", group: "CPU", type: "Temperature" },
  { key: "Te05", name: "CPU efficiency core 1", group: "CPU", type: "Temperature" },
  { key: "Tp09", name: "CPU efficiency core 1", group: "CPU", type: "Temperature" },
  { key: "Tp1h", name: "CPU efficiency core 1", group: "CPU", type: "Temperature" },
  { key: "Te0L", name: "CPU efficiency core 2", group: "CPU", type: "Temperature" },
  { key: "Te0S", name: "CPU efficiency core 2", group: "CPU", type: "Temperature" },
  { key: "Tp0T", name: "CPU efficiency core 2", group: "CPU", type: "Temperature" },
  { key: "Tp1t", name: "CPU efficiency core 2", group: "CPU", type: "Temperature" },
  { key: "Te09", name: "CPU efficiency core 3", group: "CPU", type: "Temperature" },
  { key: "Te0P", name: "CPU efficiency core 3", group: "CPU", type: "Temperature" },
  { key: "Tp1p", name: "CPU efficiency core 3", group: "CPU", type: "Temperature" },
  { key: "Te0H", name: "CPU efficiency core 4", group: "CPU", type: "Temperature" },
  { key: "Te0S", name: "CPU efficiency core 4", group: "CPU", type: "Temperature" },
  { key: "Tp1l", name: "CPU efficiency core 4", group: "CPU", type: "Temperature" },
  { key: "PC0G", name: "CPU GFX", group: "CPU", type: "Power" },
  { key: "TC0H", name: "CPU heatsink", group: "CPU", type: "Temperature" },
  { key: "VCAC", name: "CPU IA", group: "CPU", type: "Voltage" },
  { key: "TCAD", name: "CPU package", group: "CPU", type: "Temperature" },
  { key: "PCPC", name: "CPU Package", group: "CPU", type: "Power" },
  { key: "PCPT", name: "CPU Package total", group: "CPU", type: "Power" },
  { key: "PCPR", name: "CPU Package total (SMC)", group: "CPU", type: "Power" },
  { key: "Tf04", name: "CPU performance core 1", group: "CPU", type: "Temperature" },
  { key: "Tp01", name: "CPU performance core 1", group: "CPU", type: "Temperature" },
  { key: "Tp0O", name: "CPU performance core 1", group: "CPU", type: "Temperature" },
  { key: "Tf4B", name: "CPU performance core 10", group: "CPU", type: "Temperature" },
  { key: "Tp0p", name: "CPU performance core 10", group: "CPU", type: "Temperature" },
  { key: "Tf4D", name: "CPU performance core 11", group: "CPU", type: "Temperature" },
  { key: "Tp0u", name: "CPU performance core 11", group: "CPU", type: "Temperature" },
  { key: "Tf4E", name: "CPU performance core 12", group: "CPU", type: "Temperature" },
  { key: "Tp0y", name: "CPU performance core 12", group: "CPU", type: "Temperature" },
  { key: "Tf09", name: "CPU performance core 2", group: "CPU", type: "Temperature" },
  { key: "Tp05", name: "CPU performance core 2", group: "CPU", type: "Temperature" },
  { key: "Tp0R", name: "CPU performance core 2", group: "CPU", type: "Temperature" },
  { key: "Tf0A", name: "CPU performance core 3", group: "CPU", type: "Temperature" },
  { key: "Tp09", name: "CPU performance core 3", group: "CPU", type: "Temperature" },
  { key: "Tp0D", name: "CPU performance core 3", group: "CPU", type: "Temperature" },
  { key: "Tp0U", name: "CPU performance core 3", group: "CPU", type: "Temperature" },
  { key: "Tf0B", name: "CPU performance core 4", group: "CPU", type: "Temperature" },
  { key: "Tp0D", name: "CPU performance core 4", group: "CPU", type: "Temperature" },
  { key: "Tp0H", name: "CPU performance core 4", group: "CPU", type: "Temperature" },
  { key: "Tp0X", name: "CPU performance core 4", group: "CPU", type: "Temperature" },
  { key: "Tf0D", name: "CPU performance core 5", group: "CPU", type: "Temperature" },
  { key: "Tp0a", name: "CPU performance core 5", group: "CPU", type: "Temperature" },
  { key: "Tp0L", name: "CPU performance core 5", group: "CPU", type: "Temperature" },
  { key: "Tp0V", name: "CPU performance core 5", group: "CPU", type: "Temperature" },
  { key: "Tp0X", name: "CPU performance core 5", group: "CPU", type: "Temperature" },
  { key: "Tf0E", name: "CPU performance core 6", group: "CPU", type: "Temperature" },
  { key: "Tp0b", name: "CPU performance core 6", group: "CPU", type: "Temperature" },
  { key: "Tp0d", name: "CPU performance core 6", group: "CPU", type: "Temperature" },
  { key: "Tp0P", name: "CPU performance core 6", group: "CPU", type: "Temperature" },
  { key: "Tp0Y", name: "CPU performance core 6", group: "CPU", type: "Temperature" },
  { key: "Tf44", name: "CPU performance core 7", group: "CPU", type: "Temperature" },
  { key: "Tp0b", name: "CPU performance core 7", group: "CPU", type: "Temperature" },
  { key: "Tp0f", name: "CPU performance core 7", group: "CPU", type: "Temperature" },
  { key: "Tp0g", name: "CPU performance core 7", group: "CPU", type: "Temperature" },
  { key: "Tp0X", name: "CPU performance core 7", group: "CPU", type: "Temperature" },
  { key: "Tf49", name: "CPU performance core 8", group: "CPU", type: "Temperature" },
  { key: "Tp0b", name: "CPU performance core 8", group: "CPU", type: "Temperature" },
  { key: "Tp0e", name: "CPU performance core 8", group: "CPU", type: "Temperature" },
  { key: "Tp0j", name: "CPU performance core 8", group: "CPU", type: "Temperature" },
  { key: "Tf4A", name: "CPU performance core 9", group: "CPU", type: "Temperature" },
  { key: "Tp0m", name: "CPU performance core 9", group: "CPU", type: "Temperature" },
  { key: "TC0P", name: "CPU proximity", group: "CPU", type: "Temperature" },
  { key: "Tp00", name: "CPU super core 1", group: "CPU", type: "Temperature" },
  { key: "Tp04", name: "CPU super core 2", group: "CPU", type: "Temperature" },
  { key: "Tp08", name: "CPU super core 3", group: "CPU", type: "Temperature" },
  { key: "Tp0C", name: "CPU super core 4", group: "CPU", type: "Temperature" },
  { key: "Tp0G", name: "CPU super core 5", group: "CPU", type: "Temperature" },
  { key: "Tp0K", name: "CPU super core 6", group: "CPU", type: "Temperature" },
  { key: "VCSC", name: "CPU System Agent", group: "CPU", type: "Voltage" },
  { key: "PCTR", name: "CPU Total", group: "CPU", type: "Power" },
  { key: "PCEC", name: "CPU VccEDRAM", group: "CPU", type: "Power" },
  { key: "PG0C", name: "GPU", group: "GPU", type: "Power" },
  { key: "VG0C", name: "GPU", group: "GPU", type: "Voltage" },
  { key: "PG0R", name: "GPU 1", group: "GPU", type: "Power" },
  { key: "Tf14", name: "GPU 1", group: "GPU", type: "Temperature" },
  { key: "Tg05", name: "GPU 1", group: "GPU", type: "Temperature" },
  { key: "Tg0f", name: "GPU 1", group: "GPU", type: "Temperature" },
  { key: "Tg0G", name: "GPU 1", group: "GPU", type: "Temperature" },
  { key: "Tg0U", name: "GPU 1", group: "GPU", type: "Temperature" },
  { key: "Tg1U", name: "GPU 1", group: "GPU", type: "Temperature" },
  { key: "PG1R", name: "GPU 2", group: "GPU", type: "Power" },
  { key: "Tf18", name: "GPU 2", group: "GPU", type: "Temperature" },
  { key: "Tg0D", name: "GPU 2", group: "GPU", type: "Temperature" },
  { key: "Tg0H", name: "GPU 2", group: "GPU", type: "Temperature" },
  { key: "Tg0j", name: "GPU 2", group: "GPU", type: "Temperature" },
  { key: "Tg0X", name: "GPU 2", group: "GPU", type: "Temperature" },
  { key: "Tg1k", name: "GPU 2", group: "GPU", type: "Temperature" },
  { key: "Tf19", name: "GPU 3", group: "GPU", type: "Temperature" },
  { key: "Tg0d", name: "GPU 3", group: "GPU", type: "Temperature" },
  { key: "Tg0K", name: "GPU 3", group: "GPU", type: "Temperature" },
  { key: "Tg0L", name: "GPU 3", group: "GPU", type: "Temperature" },
  { key: "Tf1A", name: "GPU 4", group: "GPU", type: "Temperature" },
  { key: "Tg0g", name: "GPU 4", group: "GPU", type: "Temperature" },
  { key: "Tg0L", name: "GPU 4", group: "GPU", type: "Temperature" },
  { key: "Tg0T", name: "GPU 4", group: "GPU", type: "Temperature" },
  { key: "Tf24", name: "GPU 5", group: "GPU", type: "Temperature" },
  { key: "Tg0d", name: "GPU 5", group: "GPU", type: "Temperature" },
  { key: "Tg0j", name: "GPU 5", group: "GPU", type: "Temperature" },
  { key: "Tf28", name: "GPU 6", group: "GPU", type: "Temperature" },
  { key: "Tg0e", name: "GPU 6", group: "GPU", type: "Temperature" },
  { key: "Tg1Y", name: "GPU 6", group: "GPU", type: "Temperature" },
  { key: "Tf29", name: "GPU 7", group: "GPU", type: "Temperature" },
  { key: "Tg0j", name: "GPU 7", group: "GPU", type: "Temperature" },
  { key: "Tg1c", name: "GPU 7", group: "GPU", type: "Temperature" },
  { key: "Tf2A", name: "GPU 8", group: "GPU", type: "Temperature" },
  { key: "Tg0k", name: "GPU 8", group: "GPU", type: "Temperature" },
  { key: "Tg1g", name: "GPU 8", group: "GPU", type: "Temperature" },
  { key: "TGDD", name: "GPU AMD Radeon", group: "GPU", type: "Temperature" },
  { key: "TG0D", name: "GPU diode", group: "GPU", type: "Temperature" },
  { key: "TG0H", name: "GPU heatsink", group: "GPU", type: "Temperature" },
  { key: "PCPG", name: "GPU Intel Graphics", group: "GPU", type: "Power" },
  { key: "TCGC", name: "GPU Intel Graphics", group: "GPU", type: "Temperature" },
  { key: "VCTC", name: "GPU Intel Graphics", group: "GPU", type: "Voltage" },
  { key: "TG0P", name: "GPU proximity", group: "GPU", type: "Temperature" },
  { key: "PCGC", name: "Intel GPU", group: "GPU", type: "Power" },
  { key: "PCGM", name: "Intel GPU (IMON)", group: "GPU", type: "Power" },
  { key: "VV9S", name: "12V", group: "Sensors", type: "Voltage" },
  { key: "VP0R", name: "12V rail", group: "Sensors", type: "Voltage" },
  { key: "Vp0C", name: "12V vcc", group: "Sensors", type: "Voltage" },
  { key: "VR3R", name: "3.3V", group: "Sensors", type: "Voltage" },
  { key: "VV2S", name: "3V", group: "Sensors", type: "Voltage" },
  { key: "VV1S", name: "5V", group: "Sensors", type: "Voltage" },
  { key: "TaLP", name: "Airflow left", group: "Sensors", type: "Temperature" },
  { key: "TaRF", name: "Airflow right", group: "Sensors", type: "Temperature" },
  { key: "gas gauge battery", name: "Battery", group: "Sensors", type: "Temperature" },
  { key: "IBAC", name: "Battery", group: "Sensors", type: "Current" },
  { key: "PPBR", name: "Battery", group: "Sensors", type: "Power" },
  { key: "IDBR", name: "Brightness", group: "Sensors", type: "Current" },
  { key: "IC0R", name: "CPU High side", group: "Sensors", type: "Current" },
  { key: "ID0R", name: "DC In", group: "Sensors", type: "Current" },
  { key: "PDTR", name: "DC In", group: "Sensors", type: "Power" },
  { key: "VD0R", name: "DC In", group: "Sensors", type: "Voltage" },
  { key: "PBwo", name: "Display Backlight", group: "Sensors", type: "Power" },
  { key: "IG0R", name: "GPU High side", group: "Sensors", type: "Current" },
  { key: "Tm02", name: "Memory 1", group: "Sensors", type: "Temperature" },
  { key: "Tm06", name: "Memory 2", group: "Sensors", type: "Temperature" },
  { key: "Tm08", name: "Memory 3", group: "Sensors", type: "Temperature" },
  { key: "Tm09", name: "Memory 4", group: "Sensors", type: "Temperature" },
  { key: "Tm0p", name: "Memory Proximity 1", group: "Sensors", type: "Temperature" },
  { key: "Tm1p", name: "Memory Proximity 2", group: "Sensors", type: "Temperature" },
  { key: "Tm2p", name: "Memory Proximity 3", group: "Sensors", type: "Temperature" },
  { key: "PMTR", name: "Memory Total", group: "Sensors", type: "Power" },
  { key: "VeES", name: "PCI 12V", group: "Sensors", type: "Voltage" },
  { key: "PDBR", name: "Power Delivery Brightness", group: "Sensors", type: "Power" },
  { key: "PC3C", name: "RAM", group: "Sensors", type: "Power" },
  { key: "PSTR", name: "System Total", group: "Sensors", type: "Power" },
  { key: "IU1R", name: "Thunderbolt Left", group: "Sensors", type: "Current" },
  { key: "PU1R", name: "Thunderbolt Left", group: "Sensors", type: "Power" },
  { key: "IU2R", name: "Thunderbolt Right", group: "Sensors", type: "Current" },
  { key: "PU2R", name: "Thunderbolt Right", group: "Sensors", type: "Power" },
  { key: "TW0P", name: "Airport", group: "Systems", type: "Temperature" },
  { key: "TB1T", name: "Battery", group: "Systems", type: "Temperature" },
  { key: "TB1T", name: "Battery 1", group: "Systems", type: "Temperature" },
  { key: "TB2T", name: "Battery 2", group: "Systems", type: "Temperature" },
  { key: "Vb0R", name: "CMOS", group: "Systems", type: "Voltage" },
  { key: "TL0P", name: "Display", group: "Systems", type: "Temperature" },
  { key: "Tm0P", name: "Mainboard", group: "Systems", type: "Temperature" },
  { key: "VM0R", name: "Memory", group: "Systems", type: "Voltage" },
  { key: "TH0x", name: "NAND", group: "Systems", type: "Temperature" },
  { key: "TN0D", name: "Northbridge diode", group: "Systems", type: "Temperature" },
  { key: "TN0H", name: "Northbridge heatsink", group: "Systems", type: "Temperature" },
  { key: "TN0P", name: "Northbridge proximity", group: "Systems", type: "Temperature" },
  { key: "Tp0P", name: "Powerboard", group: "Systems", type: "Temperature" },
  { key: "TTLD", name: "Thunderbolt left", group: "Systems", type: "Temperature" },
  { key: "TTRD", name: "Thunderbolt right", group: "Systems", type: "Temperature" },
];

export const CATALOG_TOTALS = {
  /** Entries in the shipped table, wildcard families included. */
  entries: 200,
  literalKeys: 171,
  groups: {"CPU":77,"GPU":45,"Sensors":34,"Systems":15},
  types: {"Power":24,"Temperature":126,"Voltage":14,"Current":7},
};
